name: flutter_contact
version: 0.9.1+7
homepage: https://github.com/SunnyApp/flutter_contact
description: A Flutter plugin to retrieve, create and save contacts and contact-related events on Android and iOS devices.
maintainer: Eric Martineau
environment: 
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=1.10.0'
dependencies: 
  collection: ^1.15.0
  dartxx: ^0.5.3+2
  equatable: ^2.0.3
#  flexidate: ^0.8.0+3
#  flexidate:
#    git:
#      url: https://github.com/kadersaka/flexidate

  intl: ^0.17.0
  logging: ^1.0.2
  logging_config: ^0.6.7+7
  quiver: ^3.0.1+1
  uuid: ^3.0.5


#  collection: ^1.15.0
  dartx: ^0.7.1
#  dartxx: ^0.5.3+2
#  equatable: ^2.0.3
  inflection3: ^0.5.3+2
#  intl: ^0.17.0
#  logging: ^1.0.2
  timezone: ^0.9.0

  flutter: 
    sdk: flutter
dev_dependencies: 
  pedantic: ^1.11.1
  flutter_test: 
    sdk: flutter
flutter: 
  plugin: 
    platforms: 
      android: 
        package: co.sunnyapp.flutter_contact
        pluginClass: FlutterContactPlugin
      ios: 
        pluginClass: FlutterContactPlugin


#https://github.com/kadersaka/flexidate